export const Ingredient_ADDED = 'INGREDIENT_ADDED';
export const INGREDIENT_REMOVE = 'INGREDIENT_REMOVE';
export const UPDATE_PURCHASABLE = 'UPDATE_PURCHASABLE';
export const RESET_INGREDIENT = 'RESET_INGREDIENT';
export const LOADING_ORDER = 'LOADING_ORDER';
export const LOADING_ORDER_FAILD = 'LOADING_ORDER_FAILD'

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';




